version: "3.8"
services:
  api-ledger:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "443:443"

  db:
    image: mariadb:10.6
    env_file: /Users/levtk/go/src/levtk/sequra/.env #this path should be where you have your source code for this project
    ports:
      - "3306:3306"

