version: "3.8"
services:
  api-ledger:
    build:
      dockerfile: Dockerfile
    container_name: api
    networks: [backend]
    ports:
      - "8080:8080"
      - "443:443"
    depends_on: [db]

  db:
    image: mariadb:10.6
    container_name: db
    env_file: /Users/levtk/go/src/levtk/sequra/.env #this path should be where you have your source code for this project
    networks: [backend]
    ports:
      - "3306:3306"
networks:
  backend:
  frontend:

